
package info._7chapters.webservice.ch02.tsdoc;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://ws.ts.ch02.webservice._7chapters.info/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsString", targetNamespace = "http://ws.ts.ch02.webservice._7chapters.info/", className = "info._7chapters.webservice.ch02.tsdoc.GetTimeAsString")
    @ResponseWrapper(localName = "getTimeAsStringResponse", targetNamespace = "http://ws.ts.ch02.webservice._7chapters.info/", className = "info._7chapters.webservice.ch02.tsdoc.GetTimeAsStringResponse")
    public String getTimeAsString();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsElapsed", targetNamespace = "http://ws.ts.ch02.webservice._7chapters.info/", className = "info._7chapters.webservice.ch02.tsdoc.GetTimeAsElapsed")
    @ResponseWrapper(localName = "getTimeAsElapsedResponse", targetNamespace = "http://ws.ts.ch02.webservice._7chapters.info/", className = "info._7chapters.webservice.ch02.tsdoc.GetTimeAsElapsedResponse")
    public long getTimeAsElapsed();

}
