
package info._7chapters.webservice.ch02.tsdoc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TimeServerImplService", targetNamespace = "http://ws.ts.ch02.webservice._7chapters.info/", wsdlLocation = "http://127.0.0.1:9876/ts_doc?wsdl")
public class TimeServerImplService
    extends Service
{

    private final static URL TIMESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(info._7chapters.webservice.ch02.tsdoc.TimeServerImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = info._7chapters.webservice.ch02.tsdoc.TimeServerImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9876/ts_doc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9876/ts_doc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TIMESERVERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TimeServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeServerImplService() {
        super(TIMESERVERIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.ts.ch02.webservice._7chapters.info/", "TimeServerImplService"));
    }

    /**
     * 
     * @return
     *     returns TimeServer
     */
    @WebEndpoint(name = "TimeServerImplPort")
    public TimeServer getTimeServerImplPort() {
        return super.getPort(new QName("http://ws.ts.ch02.webservice._7chapters.info/", "TimeServerImplPort"), TimeServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimeServer
     */
    @WebEndpoint(name = "TimeServerImplPort")
    public TimeServer getTimeServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ts.ch02.webservice._7chapters.info/", "TimeServerImplPort"), TimeServer.class, features);
    }

}
